# Generated by Django 3.2.16 on 2022-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0003_alter_pontosturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
