# Generated by Django 3.2.16 on 2022-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0004_pontosturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
