# Generated by Django 3.2.16 on 2022-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pontosturistico_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
